version: "3.8"
services:
  reverse-proxy:
    build: reverse-proxy/.
    ports:
      - 8000:80
    networks:
      - net
    environment:
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 80
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    depends_on:
      - "frontend"
      - "backend"
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        BUILD_WEBSOCKET_ROOT_ADDRESS: ws://localhost:8000/api
        BUILD_BACKEND_ROOT_ADDRESS: http://localhost:8000/api
    networks:
      - net
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - net
    environment:
      APP_ENVIRONMENT: production

networks:
  net: {}
